### ISSUE TITLE
Use ng-show instead of ng-if if not performance-critical

### ISSUE THREAD

**Issue by andrenarchy** [paperhive/paperhive-frontend#22]
`ng-show` simply hides elements while `ng-if` actually removes them from the DOM.

Especially when custom handlers are in play (e.g., pdf selection), `ng-if` leads to nasty bugs because event handlers may be lost. I suggest we use `ng-show` everywhere unless the element is performance-critical. See also [here](http://stackoverflow.com/a/21870119).

**Comment by nschloe** [comment]
> ng-if leads to nasty bugs because event handlers may be lost.

Indeed, see <https://github.com/paperhub/paperhub-frontend/blob/master/src/templates/article/text/index.html#L15> for an example.

I don't see why we should keep the element in the DOM tree if we don't show it though. If we need to keep it for the event handler, use `ng-show`, otherwise `ng-if`. Seems simple enough?

**Comment by andrenarchy** [comment]
The problem is: all event handlers of child elements will also disappear with `ng-if`. So how can we guarantee that there's no element below that needs event handlers? Maybe it's not a problem at all if event handlers are re-attached properly?

**Comment by andrenarchy** [comment]
There's no problem with `ng-if` as long as all directives are properly implemented. If setup of a directive is expensive, using `ng-show` may be an option.

Closing since this isn't an actual issue.
