### ISSUE TITLE
invalid pages don't return 404

### ISSUE THREAD

**Issue by nschloe** [paperhive/paperhive-frontend#274]
```
curl -v https://dev.paperhive.org/frontend/master/invalid
```

**Comment by andrenarchy** [comment]
URLs that do not resolve to an actual file (e.g., static assets) automatically resolve to the index.html file in order to support URLs without a hash (i.e., `html5Mode`).

Search engines will get 404's via prerender when https://github.com/paperhive/paperhive-launch/pull/15 is merged.

We'll probably be able to provide proper return codes for all clients with angular2's server-side rendering capabilities.

Pls reopen if this is still an issue. :)
