### ISSUE TITLE
Discussion/reply updates are not live-synced in thread view

### ISSUE THREAD

**Issue by andrenarchy** [paperhive/paperhive-frontend#403]
Updating a discussion or a reply in the pdf view does not update the thread view (in another browser window).

**Comment by nschloe** [comment]
This issue exists because of restrictions in the route config. We have to hand over ALL discussions to the discussion-thread-view component, and extract the current discussion by the route parameters there. Deep watching `$ctrl.discussions.stored` does for some reason not report changes in replies in any of the stored discussions.
Will likely resolve once we use the component router.
